spring:
  application:
    name: mt-gateway
  cloud:
    gateway:
      routes:
      - id: roles
        uri: lb://misc-service
        predicates:
        - Path=/roles
      - id: contact
        uri: lb://contact-service
        predicates:
        - Path=/contact
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
